/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.5).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package ec.bp.devops.api;

import ec.bp.devops.model.Message;
import ec.bp.devops.model.ModelApiResponse;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;
import java.util.concurrent.CompletableFuture;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-07-05T03:09:44.410Z")

@Api(value = "Message", description = "the Message API")
public interface MessageApi {

    @ApiOperation(value = "Send message with request data", nickname = "sendMessage", notes = "Send message", response = ModelApiResponse.class, authorizations = {
            @Authorization(value = "APIKeyHeader")
    }, tags = {"message",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "200 response", response = ModelApiResponse.class),
            @ApiResponse(code = 404, message = "404 response", response = ModelApiResponse.class),
            @ApiResponse(code = 500, message = "500 response", response = ModelApiResponse.class)})
    @RequestMapping(value = "/DevOps",
            produces = {"application/json"},
            consumes = {"application/json"},
            method = RequestMethod.POST)
    CompletableFuture<ResponseEntity<ModelApiResponse>> sendMessage(@RequestHeader(value = "X-Parse-REST-API-Key", required = true) String apiKey, @ApiParam(value = "", required = true) @Valid @RequestBody Message messageRequest);

}
